Repository Sweaty-Bacon-Ducks/Steamy, pull requests merged in 2018-11, with the labels that each got.

#50 Changed folder hierarchy
  Project/Assets/Materials/sprite_realExplosion_c.mat
  Project/Assets/Materials/sprite_realExplosion_c.mat.meta
  Project/Assets/ScriptableObjects.meta
  Project/Assets/ScriptableObjects/Healing.asset
  Project/Assets/ScriptableObjects/Healing.asset.meta
  Project/Assets/Sprites/Effects.meta
  Project/Assets/Sprites/Effects/sprite_realExplosion_c.png
  Project/Assets/Sprites/Effects/sprite_realExplosion_c.png.meta
  Project/Assets/_Scenes/MenuTest.unity
  Project/Assets/_Scenes/MenuTest.unity.meta
  Project/Assets/_Scenes/Online/TestScene.unity
  Project/Assets/_Scenes/Platform test.unity
  Project/Assets/_Scenes/Platform test.unity.meta
  Project/Assets/_Scripts/Other/CameraMouseFollow.cs
  Project/Assets/_Scripts/Other/CameraMouseFollow.cs.meta
  Project/Assets/_Scripts/Other/ExplosionCollector.cs
  Project/Assets/_Scripts/Other/ExplosionCollector.cs.meta
  Project/Assets/_Scripts/Other/Parallax.cs
  Project/Assets/_Scripts/Other/Parallax.cs.meta
  Project/Assets/_Scripts/Platforms.meta
  Project/Assets/_Scripts/Platforms/BouncyArena.cs
  Project/Assets/_Scripts/Platforms/BouncyArena.cs.meta
  Project/Assets/_Scripts/Platforms/Buff.cs
  Project/Assets/_Scripts/Platforms/Buff.cs.meta
  Project/Assets/_Scripts/Platforms/BuffZone.cs
  Project/Assets/_Scripts/Platforms/BuffZone.cs.meta
  Project/Assets/_Scripts/Platforms/StageHazard.cs
  Project/Assets/_Scripts/Platforms/StageHazard.cs.meta
  Project/Assets/_Scripts/Platforms/StatusEffects.cs
  Project/Assets/_Scripts/Platforms/StatusEffects.cs.meta
  Project/Assets/_Scripts/Platforms/platformBehaviour.cs
  Project/Assets/_Scripts/Platforms/platformBehaviour.cs.meta
  Project/Assets/_Scripts/Weapon Code/PhysicsWeaponController.cs
  Project/Assets/_Scripts/Weapon Code/PhysicsWeaponController.cs.meta
Labels: fix

#51 Added test character model
  Project/Assets/Models.meta
  Project/Assets/Models/TestModel.blend
  Project/Assets/Models/TestModel.blend.meta
Labels: animations, graphics

#61 Added the base of WeaponSystem
  Project/Assets/_Scripts/_new_Scripts/Weapons.meta
  Project/Assets/_Scripts/_new_Scripts/Weapons/IAttackable.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/IAttackable.cs.meta
  Project/Assets/_Scripts/_new_Scripts/Weapons/MeleeViewModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/MeleeViewModel.cs.meta
  Project/Assets/_Scripts/_new_Scripts/Weapons/PhysicsGunModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/PhysicsGunModel.cs.meta
  Project/Assets/_Scripts/_new_Scripts/Weapons/PhysicsGunViewModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/PhysicsGunViewModel.cs.meta
  Project/Assets/_Scripts/_new_Scripts/Weapons/RaycastGunModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/RaycastGunModel.cs.meta
  Project/Assets/_Scripts/_new_Scripts/Weapons/RaycastGunViewModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/RaycastGunViewModel.cs.meta
  Project/Assets/_Scripts/_new_Scripts/Weapons/WeaponModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/WeaponModel.cs.meta
  Project/Assets/_Scripts/_new_Scripts/Weapons/WeaponViewModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/WeaponViewModel.cs.meta
Labels: functionality
