Repository Sweaty-Bacon-Ducks/Steamy, pull requests merged in 2018-12, with the labels that each got.

#62 Movement corrections and camera
  Project/Assets/MovementTest.unity
  Project/Assets/Scripts/Player Code/Camera.meta
  Project/Assets/Scripts/Player Code/Camera/CameraFollow.cs
  Project/Assets/Scripts/Player Code/Camera/CameraFollow.cs.meta
  Project/Assets/Scripts/Player Code/MotionModes/AnimatedRunMode.cs
Labels: fix, functionality

#68 Updated AnimationController
  Project/Assets/AnimationControllers.meta
  Project/Assets/Animations/BasePlayerAnimationController.controller
  Project/Assets/Models/Characters.meta
  Project/Assets/Models/TestModel.blend
  Project/Assets/Scenes.meta
  Project/Assets/Scenes/Online.meta
  Project/Assets/ScriptableObjects/Character.meta
  Project/Assets/ScriptableObjects/Character/Locomotion.meta
  Project/Assets/ScriptableObjects/Input.meta
  Project/Assets/Scripts.meta
  Project/Assets/Scripts/Player Code.meta
  Project/Assets/Scripts/Player Code/InputControllers.meta
  Project/Assets/Scripts/Player Code/InputControllers/Platform dependent.meta
  Project/Assets/Scripts/Player Code/InputControllers/Platform dependent/Windows.meta
  Project/Assets/Scripts/Player Code/MotionModes.meta
  Project/Assets/Scripts/Utility.meta
  Project/Assets/Scripts/Utility/Reflection.meta
  Project/Assets/Scripts/Utility/Xml.meta
  Project/Assets/_Prefabs/Arms.mask
  Project/Assets/_Prefabs/Arms.mask.meta
  Project/Assets/_Prefabs/Body.mask
  Project/Assets/_Prefabs/Body.mask.meta
  Project/Assets/_Prefabs/Head.mask
  Project/Assets/_Prefabs/Head.mask.meta
  Project/Assets/_Prefabs/TestModel.blend
  Project/Assets/_Prefabs/TestModel.blend.meta
  Project/Assets/_Scenes.meta
  Project/Assets/_Scenes/Online.meta
  Project/Assets/_Scenes/Online/TestScene.unity
  Project/Assets/_Scripts.meta
  Project/Assets/_Scripts/_new_Scripts/Player Code.meta
  Project/Assets/_Scripts/_new_Scripts/Player Code/MotionModes.meta
  Project/Assets/_Scripts/_new_Scripts/Test.meta
  Project/Assets/_Scripts/_new_Scripts/Test/AnimationConfigurator.cs
  Project/Assets/_Scripts/_new_Scripts/Test/AnimationConfigurator.cs.meta
  Project/Assets/_Scripts/_new_Scripts/Utility.meta
  Project/Assets/_Scripts/_new_Scripts/Utility/Reflection.meta
  Project/Assets/_Scripts/_new_Scripts/Utility/Xml.meta
Labels: animations, functionality

#71 Fixed Compilation Errors
  Project/Assets/Editor.meta
  Project/Assets/Editor/EditorModeTests.meta
  Project/Assets/ScriptableObjects/Character/Locomotion/AnimatedRunMode.asset
  Project/Assets/Scripts.meta
  Project/Assets/Scripts/Player Code.meta
  Project/Assets/_Prefabs/Characters/Bob/Bob.prefab
  Project/Assets/_Scenes/MovementTest.unity
  Project/Assets/_Scripts/_new_Scripts/IDefault.cs.meta
  Project/Assets/_Scripts/_new_Scripts/Player Code/CharacterModel.cs
  Project/Assets/_Scripts/_new_Scripts/Player Code/MotionModes/AnimatedRunMode.cs
Labels: fix
