Repository Sweaty-Bacon-Ducks/Steamy, pull requests merged in 2019-02, with the labels that each got.

#80 Zmigrowano unity na 2018.3.3
  Project/Logs/Packages-Update.log
  Project/Packages/manifest.json
  Project/ProjectSettings/ProjectSettings.asset
  Project/ProjectSettings/ProjectVersion.txt
  Project/ProjectSettings/VFXManager.asset
Labels: maintenance

#85 Fix/shooting refactor
  Project/Assets/_Scripts/_new_Scripts/Player Code/CharacterViewModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/MeleeViewModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/PhysicsGunDefault.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/PhysicsGunViewModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/RaycastGunDefault.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/RaycastGunModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/RaycastGunViewModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/WeaponDefault.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/WeaponModel.cs
  Project/Assets/_Scripts/_new_Scripts/Weapons/WeaponViewModel.cs
Labels: fix

#87 Added object registry
  Project/Assets/_Scripts/_new_Scripts/IObjectRegistry.cs
  Project/Assets/_Scripts/_new_Scripts/IObjectRegistry.cs.meta
Labels: functionality
